"""update schema

Revision ID: d0b2c0f348d7
Revises: 0007_enable_pgvector
Create Date: 2026-05-21 20:46:14.323472
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'd0b2c0f348d7'
down_revision = '0007_enable_pgvector'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
